добавляем functions.js
htmlacademy-javascript/2077591-kekstagram-28 pull request #3
Opened 2023-02-20 08:00 UTC by RomanBelyankin

не понимаю пока что как сделать вторую половину задания

2023-02-20 13:09 UTC, o-bender requested changes
1. Используй camelCase
2. Не реализована функция поиска палиндрома. Да, ты написал две функции разворота строки reverseString и проверки, но функции isPalindrome нет.
3. console.log
4. reverseString объявлена дважды из-за этого не проходят тесты
5. не реализована функция "Функция, которая принимает три параметра: исходную строку, минимальную длину и строку с добавочными символами — и возвращает исходную строку, дополненную указанными символами до заданной длины."

2023-02-20 13:09 UTC, o-bender commented on js/functions.js
> +console.log (a.length);
Удаляй console.log перед отправкой на проверку. Линтер всё равно не пропустит их.

2023-02-23 08:09 UTC, RomanBelyankin commented on js/functions.js
> +console.log (a.length);
принял, буду исправлять

2023-02-26 08:07 UTC, RomanBelyankin commented on js/functions.js
> +console.log (a.length);
5й пункт "Функция, которая принимает три параметра" - достаточно сложная( подсмотрел как делать на видеоразоре

2023-02-26 14:33 UTC, o-bender requested changes
1. Исправь ошибки найденные линтером
2. В будущем используй стрелочные функции
3. Используй синтаксис квадратных скобок для доступа к элементу массива `myArray[i]`. Метод at не так чтобы часто используется. И в будущем на каждом ревью тебя будут просить писать скобки вместо at))
4. stringLength и checkLength идентичны. Удали одну из них

2023-02-27 07:26 UTC, merged